/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Amount;
import java.io.IOException;

/**
 * AffiliatePayout
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class AffiliatePayout {
  @SerializedName("CPC")
  private Amount CPC = null;

  @SerializedName("CPA")
  private Amount CPA = null;

  @SerializedName("CPS")
  private Amount CPS = null;

  public AffiliatePayout CPC(Amount CPC) {
    this.CPC = CPC;
    return this;
  }

   /**
   * See https://en.wikipedia.org/wiki/Pay_per_click for commission earned when the provided deep link is clicked
   * @return CPC
  **/
  @ApiModelProperty(value = "See https://en.wikipedia.org/wiki/Pay_per_click for commission earned when the provided deep link is clicked")
  public Amount getCPC() {
    return CPC;
  }

  public void setCPC(Amount CPC) {
    this.CPC = CPC;
  }

  public AffiliatePayout CPA(Amount CPA) {
    this.CPA = CPA;
    return this;
  }

   /**
   * See https://en.wikipedia.org/wiki/Cost_per_action for commission earned for a given action from the provided deep link
   * @return CPA
  **/
  @ApiModelProperty(value = "See https://en.wikipedia.org/wiki/Cost_per_action for commission earned for a given action from the provided deep link")
  public Amount getCPA() {
    return CPA;
  }

  public void setCPA(Amount CPA) {
    this.CPA = CPA;
  }

  public AffiliatePayout CPS(Amount CPS) {
    this.CPS = CPS;
    return this;
  }

   /**
   * See https://en.wikipedia.org/wiki/Pay_per_sale for commission earned as a result of a booking made from the provided deep link
   * @return CPS
  **/
  @ApiModelProperty(value = "See https://en.wikipedia.org/wiki/Pay_per_sale for commission earned as a result of a booking made from the provided deep link")
  public Amount getCPS() {
    return CPS;
  }

  public void setCPS(Amount CPS) {
    this.CPS = CPS;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AffiliatePayout affiliatePayout = (AffiliatePayout) o;
    return Objects.equals(this.CPC, affiliatePayout.CPC) &&
        Objects.equals(this.CPA, affiliatePayout.CPA) &&
        Objects.equals(this.CPS, affiliatePayout.CPS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(CPC, CPA, CPS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AffiliatePayout {\n");
    
    sb.append("    CPC: ").append(toIndentedString(CPC)).append("\n");
    sb.append("    CPA: ").append(toIndentedString(CPA)).append("\n");
    sb.append("    CPS: ").append(toIndentedString(CPS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

