/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CarrierMeta;
import java.io.IOException;

/**
 * AffiliateSearchMeta
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class AffiliateSearchMeta {
  @SerializedName("carriers")
  private CarrierMeta carriers = null;

  public AffiliateSearchMeta carriers(CarrierMeta carriers) {
    this.carriers = carriers;
    return this;
  }

   /**
   * A map of meta information for each of the airlines involved in the response
   * @return carriers
  **/
  @ApiModelProperty(required = true, value = "A map of meta information for each of the airlines involved in the response")
  public CarrierMeta getCarriers() {
    return carriers;
  }

  public void setCarriers(CarrierMeta carriers) {
    this.carriers = carriers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AffiliateSearchMeta affiliateSearchMeta = (AffiliateSearchMeta) o;
    return Objects.equals(this.carriers, affiliateSearchMeta.carriers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(carriers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AffiliateSearchMeta {\n");
    
    sb.append("    carriers: ").append(toIndentedString(carriers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

