/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AffiliateSearchMeta;
import io.swagger.client.model.AffiliateSearchResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AffiliateSearchResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class AffiliateSearchResponse {
  @SerializedName("meta")
  private AffiliateSearchMeta meta = null;

  @SerializedName("results")
  private List<AffiliateSearchResult> results = null;

  public AffiliateSearchResponse meta(AffiliateSearchMeta meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Meta data about the results
   * @return meta
  **/
  @ApiModelProperty(required = true, value = "Meta data about the results")
  public AffiliateSearchMeta getMeta() {
    return meta;
  }

  public void setMeta(AffiliateSearchMeta meta) {
    this.meta = meta;
  }

  public AffiliateSearchResponse results(List<AffiliateSearchResult> results) {
    this.results = results;
    return this;
  }

  public AffiliateSearchResponse addResultsItem(AffiliateSearchResult resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<AffiliateSearchResult>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(value = "")
  public List<AffiliateSearchResult> getResults() {
    return results;
  }

  public void setResults(List<AffiliateSearchResult> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AffiliateSearchResponse affiliateSearchResponse = (AffiliateSearchResponse) o;
    return Objects.equals(this.meta, affiliateSearchResponse.meta) &&
        Objects.equals(this.results, affiliateSearchResponse.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AffiliateSearchResponse {\n");
    
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

