/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CarReservationBookingInfo;
import io.swagger.client.model.Company;
import io.swagger.client.model.Vehicle;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CarReservation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class CarReservation {
  @SerializedName("id")
  private String id = null;

  @SerializedName("pick_up")
  private String pickUp = null;

  @SerializedName("drop_off")
  private String dropOff = null;

  @SerializedName("provider")
  private Company provider = null;

  @SerializedName("origin")
  private String origin = null;

  @SerializedName("car")
  private Vehicle car = null;

  @SerializedName("traveler_ids")
  private List<String> travelerIds = null;

  @SerializedName("booking_info")
  private CarReservationBookingInfo bookingInfo = null;

  public CarReservation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Uniquely identifies this car rental reservation in this travel record. This ID is persistent, and remains the same for the lifetime of the travel record.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Uniquely identifies this car rental reservation in this travel record. This ID is persistent, and remains the same for the lifetime of the travel record.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CarReservation pickUp(String pickUp) {
    this.pickUp = pickUp;
    return this;
  }

   /**
   * Date on which the car rental will be collected from the car rental location. &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/ISO_8601\&quot;&gt;ISO 8601&lt;/a&gt; date format yyyy-MM-ddTHH.
   * @return pickUp
  **/
  @ApiModelProperty(required = true, value = "Date on which the car rental will be collected from the car rental location. <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO 8601</a> date format yyyy-MM-ddTHH.")
  public String getPickUp() {
    return pickUp;
  }

  public void setPickUp(String pickUp) {
    this.pickUp = pickUp;
  }

  public CarReservation dropOff(String dropOff) {
    this.dropOff = dropOff;
    return this;
  }

   /**
   * Date at which the car rental will end and the car will be returned to the rental location. &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/ISO_8601\&quot;&gt;ISO 8601&lt;/a&gt; date format yyyy-MM-ddTHH.
   * @return dropOff
  **/
  @ApiModelProperty(required = true, value = "Date at which the car rental will end and the car will be returned to the rental location. <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO 8601</a> date format yyyy-MM-ddTHH.")
  public String getDropOff() {
    return dropOff;
  }

  public void setDropOff(String dropOff) {
    this.dropOff = dropOff;
  }

  public CarReservation provider(Company provider) {
    this.provider = provider;
    return this;
  }

   /**
   * Details of the car company offering this rental.
   * @return provider
  **/
  @ApiModelProperty(required = true, value = "Details of the car company offering this rental.")
  public Company getProvider() {
    return provider;
  }

  public void setProvider(Company provider) {
    this.provider = provider;
  }

  public CarReservation origin(String origin) {
    this.origin = origin;
    return this;
  }

   /**
   * This car rental company office location ID. If this is an airport location, this will be the airport&#39;s &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\&quot;&gt;IATA code&lt;/a&gt;. Otherwise, this is a custom value provided by the car rental provider.
   * @return origin
  **/
  @ApiModelProperty(required = true, value = "This car rental company office location ID. If this is an airport location, this will be the airport's <a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a>. Otherwise, this is a custom value provided by the car rental provider.")
  public String getOrigin() {
    return origin;
  }

  public void setOrigin(String origin) {
    this.origin = origin;
  }

  public CarReservation car(Vehicle car) {
    this.car = car;
    return this;
  }

   /**
   * A car information object giving further details about the vehicle provided for rental.
   * @return car
  **/
  @ApiModelProperty(required = true, value = "A car information object giving further details about the vehicle provided for rental.")
  public Vehicle getCar() {
    return car;
  }

  public void setCar(Vehicle car) {
    this.car = car;
  }

  public CarReservation travelerIds(List<String> travelerIds) {
    this.travelerIds = travelerIds;
    return this;
  }

  public CarReservation addTravelerIdsItem(String travelerIdsItem) {
    if (this.travelerIds == null) {
      this.travelerIds = new ArrayList<String>();
    }
    this.travelerIds.add(travelerIdsItem);
    return this;
  }

   /**
   * Traveler identifiers to indicate the travelers to whom this car rental applies. Generally, only drivers of the vehicle will be marked in this array.
   * @return travelerIds
  **/
  @ApiModelProperty(value = "Traveler identifiers to indicate the travelers to whom this car rental applies. Generally, only drivers of the vehicle will be marked in this array.")
  public List<String> getTravelerIds() {
    return travelerIds;
  }

  public void setTravelerIds(List<String> travelerIds) {
    this.travelerIds = travelerIds;
  }

  public CarReservation bookingInfo(CarReservationBookingInfo bookingInfo) {
    this.bookingInfo = bookingInfo;
    return this;
  }

   /**
   * Additional details the status of this car rental reservation.
   * @return bookingInfo
  **/
  @ApiModelProperty(value = "Additional details the status of this car rental reservation.")
  public CarReservationBookingInfo getBookingInfo() {
    return bookingInfo;
  }

  public void setBookingInfo(CarReservationBookingInfo bookingInfo) {
    this.bookingInfo = bookingInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CarReservation carReservation = (CarReservation) o;
    return Objects.equals(this.id, carReservation.id) &&
        Objects.equals(this.pickUp, carReservation.pickUp) &&
        Objects.equals(this.dropOff, carReservation.dropOff) &&
        Objects.equals(this.provider, carReservation.provider) &&
        Objects.equals(this.origin, carReservation.origin) &&
        Objects.equals(this.car, carReservation.car) &&
        Objects.equals(this.travelerIds, carReservation.travelerIds) &&
        Objects.equals(this.bookingInfo, carReservation.bookingInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, pickUp, dropOff, provider, origin, car, travelerIds, bookingInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CarReservation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    pickUp: ").append(toIndentedString(pickUp)).append("\n");
    sb.append("    dropOff: ").append(toIndentedString(dropOff)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    car: ").append(toIndentedString(car)).append("\n");
    sb.append("    travelerIds: ").append(toIndentedString(travelerIds)).append("\n");
    sb.append("    bookingInfo: ").append(toIndentedString(bookingInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

