/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Logos;
import java.io.IOException;

/**
 * CarrierInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class CarrierInfo {
  @SerializedName("logos")
  private Logos logos = null;

  @SerializedName("name")
  private String name = null;

  public CarrierInfo logos(Logos logos) {
    this.logos = logos;
    return this;
  }

   /**
   * Logos of the airline in a variety of sizes
   * @return logos
  **/
  @ApiModelProperty(required = true, value = "Logos of the airline in a variety of sizes")
  public Logos getLogos() {
    return logos;
  }

  public void setLogos(Logos logos) {
    this.logos = logos;
  }

  public CarrierInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Display name of the airline
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Display name of the airline")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CarrierInfo carrierInfo = (CarrierInfo) o;
    return Objects.equals(this.logos, carrierInfo.logos) &&
        Objects.equals(this.name, carrierInfo.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logos, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CarrierInfo {\n");
    
    sb.append("    logos: ").append(toIndentedString(logos)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

