/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ExtremeSearchResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ExtremeSearchResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class ExtremeSearchResponse {
  @SerializedName("origin")
  private String origin = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("results")
  private List<ExtremeSearchResult> results = new ArrayList<ExtremeSearchResult>();

  public ExtremeSearchResponse origin(String origin) {
    this.origin = origin;
    return this;
  }

   /**
   * &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\&quot;&gt;IATA code&lt;/a&gt;
   * @return origin
  **/
  @ApiModelProperty(required = true, value = "<a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a>")
  public String getOrigin() {
    return origin;
  }

  public void setOrigin(String origin) {
    this.origin = origin;
  }

  public ExtremeSearchResponse currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * &lt;a href&#x3D;\&quot;http://en.wikipedia.org/wiki/ISO_4217\&quot;&gt;ISO 4217&lt;/a&gt; currency code.
   * @return currency
  **/
  @ApiModelProperty(required = true, value = "<a href=\"http://en.wikipedia.org/wiki/ISO_4217\">ISO 4217</a> currency code.")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public ExtremeSearchResponse results(List<ExtremeSearchResult> results) {
    this.results = results;
    return this;
  }

  public ExtremeSearchResponse addResultsItem(ExtremeSearchResult resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(required = true, value = "")
  public List<ExtremeSearchResult> getResults() {
    return results;
  }

  public void setResults(List<ExtremeSearchResult> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtremeSearchResponse extremeSearchResponse = (ExtremeSearchResponse) o;
    return Objects.equals(this.origin, extremeSearchResponse.origin) &&
        Objects.equals(this.currency, extremeSearchResponse.currency) &&
        Objects.equals(this.results, extremeSearchResponse.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(origin, currency, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtremeSearchResponse {\n");
    
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

