/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Fees
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class Fees {
  @SerializedName("service_fees")
  private String serviceFees = null;

  @SerializedName("creditcard_fees")
  private String creditcardFees = null;

  public Fees serviceFees(String serviceFees) {
    this.serviceFees = serviceFees;
    return this;
  }

   /**
   * The cost of any required service fees in addition to the total price
   * @return serviceFees
  **/
  @ApiModelProperty(value = "The cost of any required service fees in addition to the total price")
  public String getServiceFees() {
    return serviceFees;
  }

  public void setServiceFees(String serviceFees) {
    this.serviceFees = serviceFees;
  }

  public Fees creditcardFees(String creditcardFees) {
    this.creditcardFees = creditcardFees;
    return this;
  }

   /**
   * The cost of any fees for common credit cards, such as Visa or Mastercard, in addition to the total price
   * @return creditcardFees
  **/
  @ApiModelProperty(value = "The cost of any fees for common credit cards, such as Visa or Mastercard, in addition to the total price")
  public String getCreditcardFees() {
    return creditcardFees;
  }

  public void setCreditcardFees(String creditcardFees) {
    this.creditcardFees = creditcardFees;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fees fees = (Fees) o;
    return Objects.equals(this.serviceFees, fees.serviceFees) &&
        Objects.equals(this.creditcardFees, fees.creditcardFees);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceFees, creditcardFees);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fees {\n");
    
    sb.append("    serviceFees: ").append(toIndentedString(serviceFees)).append("\n");
    sb.append("    creditcardFees: ").append(toIndentedString(creditcardFees)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

