/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Amount;
import io.swagger.client.model.FlightReservationBound;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The flight itineraries with a ticket or transitional stored ticket (TST) in this reservation, and their prices.
 */
@ApiModel(description = "The flight itineraries with a ticket or transitional stored ticket (TST) in this reservation, and their prices.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class FlightTicket {
  @SerializedName("id")
  private String id = null;

  @SerializedName("price")
  private Amount price = null;

  @SerializedName("traveler_ids")
  private List<String> travelerIds = new ArrayList<String>();

  @SerializedName("flight_bounds")
  private List<FlightReservationBound> flightBounds = new ArrayList<FlightReservationBound>();

  public FlightTicket id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Uniquely identifies this ticket in this travel record. This ID is persistent, and remains the same for the lifetime of the travel record.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Uniquely identifies this ticket in this travel record. This ID is persistent, and remains the same for the lifetime of the travel record.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public FlightTicket price(Amount price) {
    this.price = price;
    return this;
  }

   /**
   * The cost of this ticket.
   * @return price
  **/
  @ApiModelProperty(required = true, value = "The cost of this ticket.")
  public Amount getPrice() {
    return price;
  }

  public void setPrice(Amount price) {
    this.price = price;
  }

  public FlightTicket travelerIds(List<String> travelerIds) {
    this.travelerIds = travelerIds;
    return this;
  }

  public FlightTicket addTravelerIdsItem(String travelerIdsItem) {
    this.travelerIds.add(travelerIdsItem);
    return this;
  }

   /**
   * Traveler identifiers to indicate the travelers to whom this ticket applies.
   * @return travelerIds
  **/
  @ApiModelProperty(required = true, value = "Traveler identifiers to indicate the travelers to whom this ticket applies.")
  public List<String> getTravelerIds() {
    return travelerIds;
  }

  public void setTravelerIds(List<String> travelerIds) {
    this.travelerIds = travelerIds;
  }

  public FlightTicket flightBounds(List<FlightReservationBound> flightBounds) {
    this.flightBounds = flightBounds;
    return this;
  }

  public FlightTicket addFlightBoundsItem(FlightReservationBound flightBoundsItem) {
    this.flightBounds.add(flightBoundsItem);
    return this;
  }

   /**
   * The flight itinerary for this ticket.
   * @return flightBounds
  **/
  @ApiModelProperty(required = true, value = "The flight itinerary for this ticket.")
  public List<FlightReservationBound> getFlightBounds() {
    return flightBounds;
  }

  public void setFlightBounds(List<FlightReservationBound> flightBounds) {
    this.flightBounds = flightBounds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightTicket flightTicket = (FlightTicket) o;
    return Objects.equals(this.id, flightTicket.id) &&
        Objects.equals(this.price, flightTicket.price) &&
        Objects.equals(this.travelerIds, flightTicket.travelerIds) &&
        Objects.equals(this.flightBounds, flightTicket.flightBounds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, price, travelerIds, flightBounds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightTicket {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    travelerIds: ").append(toIndentedString(travelerIds)).append("\n");
    sb.append("    flightBounds: ").append(toIndentedString(flightBounds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

