/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FlightReservationSegment;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * FlightReservationBound
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class FlightReservationBound {
  @SerializedName("flights")
  private List<FlightReservationSegment> flights = new ArrayList<FlightReservationSegment>();

  public FlightReservationBound flights(List<FlightReservationSegment> flights) {
    this.flights = flights;
    return this;
  }

  public FlightReservationBound addFlightsItem(FlightReservationSegment flightsItem) {
    this.flights.add(flightsItem);
    return this;
  }

   /**
   * The individual flights that make up this itinerary. These flights are presented in the order required to fly from the origin to the destination, and the array of flights represents a connection.
   * @return flights
  **/
  @ApiModelProperty(required = true, value = "The individual flights that make up this itinerary. These flights are presented in the order required to fly from the origin to the destination, and the array of flights represents a connection.")
  public List<FlightReservationSegment> getFlights() {
    return flights;
  }

  public void setFlights(List<FlightReservationSegment> flights) {
    this.flights = flights;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightReservationBound flightReservationBound = (FlightReservationBound) o;
    return Objects.equals(this.flights, flightReservationBound.flights);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flights);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightReservationBound {\n");
    
    sb.append("    flights: ").append(toIndentedString(flights)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

