/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FlightReservationBookingInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class FlightReservationBookingInfo {
  @SerializedName("travel_class")
  private String travelClass = null;

  @SerializedName("booking_code")
  private String bookingCode = null;

  @SerializedName("airline_record_locator")
  private String airlineRecordLocator = null;

  @SerializedName("status")
  private String status = null;

  public FlightReservationBookingInfo travelClass(String travelClass) {
    this.travelClass = travelClass;
    return this;
  }

   /**
   * The cabin class offered on this flight. An enumeration that will read either ECONOMY, PREMIUM_ECONOMY, BUSINESS or FIRST
   * @return travelClass
  **/
  @ApiModelProperty(required = true, value = "The cabin class offered on this flight. An enumeration that will read either ECONOMY, PREMIUM_ECONOMY, BUSINESS or FIRST")
  public String getTravelClass() {
    return travelClass;
  }

  public void setTravelClass(String travelClass) {
    this.travelClass = travelClass;
  }

  public FlightReservationBookingInfo bookingCode(String bookingCode) {
    this.bookingCode = bookingCode;
    return this;
  }

   /**
   * The Reservation Booking Designator code that determines the quality and terms of the flight offered for the given price. A single letter from A..Z
   * @return bookingCode
  **/
  @ApiModelProperty(required = true, value = "The Reservation Booking Designator code that determines the quality and terms of the flight offered for the given price. A single letter from A..Z")
  public String getBookingCode() {
    return bookingCode;
  }

  public void setBookingCode(String bookingCode) {
    this.bookingCode = bookingCode;
  }

  public FlightReservationBookingInfo airlineRecordLocator(String airlineRecordLocator) {
    this.airlineRecordLocator = airlineRecordLocator;
    return this;
  }

   /**
   * 6 character identifier of this travel record on the airline&#39;s system. May be the same as the global record locator.
   * @return airlineRecordLocator
  **/
  @ApiModelProperty(required = true, value = "6 character identifier of this travel record on the airline's system. May be the same as the global record locator.")
  public String getAirlineRecordLocator() {
    return airlineRecordLocator;
  }

  public void setAirlineRecordLocator(String airlineRecordLocator) {
    this.airlineRecordLocator = airlineRecordLocator;
  }

  public FlightReservationBookingInfo status(String status) {
    this.status = status;
    return this;
  }

   /**
   * An enumeration to represent the reservation status for this seat on this flight. For example&amp;colon; CONFIRMED, CANCELLED, RESCHEDULED, FLIGHT_CANCELLED, WAITLISTED.
   * @return status
  **/
  @ApiModelProperty(required = true, value = "An enumeration to represent the reservation status for this seat on this flight. For example&colon; CONFIRMED, CANCELLED, RESCHEDULED, FLIGHT_CANCELLED, WAITLISTED.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlightReservationBookingInfo flightReservationBookingInfo = (FlightReservationBookingInfo) o;
    return Objects.equals(this.travelClass, flightReservationBookingInfo.travelClass) &&
        Objects.equals(this.bookingCode, flightReservationBookingInfo.bookingCode) &&
        Objects.equals(this.airlineRecordLocator, flightReservationBookingInfo.airlineRecordLocator) &&
        Objects.equals(this.status, flightReservationBookingInfo.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(travelClass, bookingCode, airlineRecordLocator, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlightReservationBookingInfo {\n");
    
    sb.append("    travelClass: ").append(toIndentedString(travelClass)).append("\n");
    sb.append("    bookingCode: ").append(toIndentedString(bookingCode)).append("\n");
    sb.append("    airlineRecordLocator: ").append(toIndentedString(airlineRecordLocator)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

