/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Image;
import java.io.IOException;

/**
 * An image size selector used in the YapQ API response. The size should correspond the the image_size parameter used during input
 */
@ApiModel(description = "An image size selector used in the YapQ API response. The size should correspond the the image_size parameter used during input")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class ImageSize {
  @SerializedName("small")
  private Image small = null;

  @SerializedName("medium")
  private Image medium = null;

  @SerializedName("large")
  private Image large = null;

  @SerializedName("hd")
  private Image hd = null;

  public ImageSize small(Image small) {
    this.small = small;
    return this;
  }

   /**
   * Get small
   * @return small
  **/
  @ApiModelProperty(value = "")
  public Image getSmall() {
    return small;
  }

  public void setSmall(Image small) {
    this.small = small;
  }

  public ImageSize medium(Image medium) {
    this.medium = medium;
    return this;
  }

   /**
   * Get medium
   * @return medium
  **/
  @ApiModelProperty(value = "")
  public Image getMedium() {
    return medium;
  }

  public void setMedium(Image medium) {
    this.medium = medium;
  }

  public ImageSize large(Image large) {
    this.large = large;
    return this;
  }

   /**
   * Get large
   * @return large
  **/
  @ApiModelProperty(value = "")
  public Image getLarge() {
    return large;
  }

  public void setLarge(Image large) {
    this.large = large;
  }

  public ImageSize hd(Image hd) {
    this.hd = hd;
    return this;
  }

   /**
   * Get hd
   * @return hd
  **/
  @ApiModelProperty(value = "")
  public Image getHd() {
    return hd;
  }

  public void setHd(Image hd) {
    this.hd = hd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageSize imageSize = (ImageSize) o;
    return Objects.equals(this.small, imageSize.small) &&
        Objects.equals(this.medium, imageSize.medium) &&
        Objects.equals(this.large, imageSize.large) &&
        Objects.equals(this.hd, imageSize.hd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(small, medium, large, hd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageSize {\n");
    
    sb.append("    small: ").append(toIndentedString(small)).append("\n");
    sb.append("    medium: ").append(toIndentedString(medium)).append("\n");
    sb.append("    large: ").append(toIndentedString(large)).append("\n");
    sb.append("    hd: ").append(toIndentedString(hd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

