/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FlightSearchItinerary;
import io.swagger.client.model.FlightSearchPrice;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LowFareSearchResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class LowFareSearchResult {
  @SerializedName("itineraries")
  private List<FlightSearchItinerary> itineraries = null;

  @SerializedName("fare")
  private FlightSearchPrice fare = null;

  public LowFareSearchResult itineraries(List<FlightSearchItinerary> itineraries) {
    this.itineraries = itineraries;
    return this;
  }

  public LowFareSearchResult addItinerariesItem(FlightSearchItinerary itinerariesItem) {
    if (this.itineraries == null) {
      this.itineraries = new ArrayList<FlightSearchItinerary>();
    }
    this.itineraries.add(itinerariesItem);
    return this;
  }

   /**
   * Get itineraries
   * @return itineraries
  **/
  @ApiModelProperty(value = "")
  public List<FlightSearchItinerary> getItineraries() {
    return itineraries;
  }

  public void setItineraries(List<FlightSearchItinerary> itineraries) {
    this.itineraries = itineraries;
  }

  public LowFareSearchResult fare(FlightSearchPrice fare) {
    this.fare = fare;
    return this;
  }

   /**
   * The price and fare information which applies to all itineraries in this response
   * @return fare
  **/
  @ApiModelProperty(required = true, value = "The price and fare information which applies to all itineraries in this response")
  public FlightSearchPrice getFare() {
    return fare;
  }

  public void setFare(FlightSearchPrice fare) {
    this.fare = fare;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LowFareSearchResult lowFareSearchResult = (LowFareSearchResult) o;
    return Objects.equals(this.itineraries, lowFareSearchResult.itineraries) &&
        Objects.equals(this.fare, lowFareSearchResult.fare);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itineraries, fare);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LowFareSearchResult {\n");
    
    sb.append("    itineraries: ").append(toIndentedString(itineraries)).append("\n");
    sb.append("    fare: ").append(toIndentedString(fare)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

