/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.LowFareSearchResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LowFareSearchResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class LowFareSearchResponse {
  @SerializedName("currency")
  private String currency = null;

  @SerializedName("results")
  private List<LowFareSearchResult> results = null;

  public LowFareSearchResponse currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * &lt;a href&#x3D;\&quot;http://en.wikipedia.org/wiki/ISO_4217\&quot;&gt;ISO 4217&lt;/a&gt; currency code.
   * @return currency
  **/
  @ApiModelProperty(required = true, value = "<a href=\"http://en.wikipedia.org/wiki/ISO_4217\">ISO 4217</a> currency code.")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public LowFareSearchResponse results(List<LowFareSearchResult> results) {
    this.results = results;
    return this;
  }

  public LowFareSearchResponse addResultsItem(LowFareSearchResult resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<LowFareSearchResult>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(value = "")
  public List<LowFareSearchResult> getResults() {
    return results;
  }

  public void setResults(List<LowFareSearchResult> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LowFareSearchResponse lowFareSearchResponse = (LowFareSearchResponse) o;
    return Objects.equals(this.currency, lowFareSearchResponse.currency) &&
        Objects.equals(this.results, lowFareSearchResponse.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LowFareSearchResponse {\n");
    
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

