/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OtherReservationBookingInfo;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;

/**
 * OtherReservation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class OtherReservation {
  @SerializedName("id")
  private String id = null;

  @SerializedName("date")
  private LocalDate date = null;

  @SerializedName("location")
  private String location = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("traveler_ids")
  private List<String> travelerIds = new ArrayList<String>();

  @SerializedName("booking_info")
  private OtherReservationBookingInfo bookingInfo = null;

  public OtherReservation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Uniquely identifies this other reservation in this travel record. This ID is persistent, and remains the same for the lifetime of the travel record.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Uniquely identifies this other reservation in this travel record. This ID is persistent, and remains the same for the lifetime of the travel record.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OtherReservation date(LocalDate date) {
    this.date = date;
    return this;
  }

   /**
   * Date on which this other reservation will begin, in the &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/ISO_8601\&quot;&gt;ISO 8601&lt;/a&gt; date format yyyy-MM-dd.
   * @return date
  **/
  @ApiModelProperty(required = true, value = "Date on which this other reservation will begin, in the <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO 8601</a> date format yyyy-MM-dd.")
  public LocalDate getDate() {
    return date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }

  public OtherReservation location(String location) {
    this.location = location;
    return this;
  }

   /**
   * A 3 letter &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\&quot;&gt;IATA code&lt;/a&gt; that identifies where this other reservation will occur.
   * @return location
  **/
  @ApiModelProperty(required = true, value = "A 3 letter <a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a> that identifies where this other reservation will occur.")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public OtherReservation description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A free-text description of this reservation, that will inform you of its functional meaning.
   * @return description
  **/
  @ApiModelProperty(value = "A free-text description of this reservation, that will inform you of its functional meaning.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OtherReservation travelerIds(List<String> travelerIds) {
    this.travelerIds = travelerIds;
    return this;
  }

  public OtherReservation addTravelerIdsItem(String travelerIdsItem) {
    this.travelerIds.add(travelerIdsItem);
    return this;
  }

   /**
   * Traveler identifiers to indicate the travelers to whom this reservation applies.
   * @return travelerIds
  **/
  @ApiModelProperty(required = true, value = "Traveler identifiers to indicate the travelers to whom this reservation applies.")
  public List<String> getTravelerIds() {
    return travelerIds;
  }

  public void setTravelerIds(List<String> travelerIds) {
    this.travelerIds = travelerIds;
  }

  public OtherReservation bookingInfo(OtherReservationBookingInfo bookingInfo) {
    this.bookingInfo = bookingInfo;
    return this;
  }

   /**
   * The status of this reservation.
   * @return bookingInfo
  **/
  @ApiModelProperty(required = true, value = "The status of this reservation.")
  public OtherReservationBookingInfo getBookingInfo() {
    return bookingInfo;
  }

  public void setBookingInfo(OtherReservationBookingInfo bookingInfo) {
    this.bookingInfo = bookingInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OtherReservation otherReservation = (OtherReservation) o;
    return Objects.equals(this.id, otherReservation.id) &&
        Objects.equals(this.date, otherReservation.date) &&
        Objects.equals(this.location, otherReservation.location) &&
        Objects.equals(this.description, otherReservation.description) &&
        Objects.equals(this.travelerIds, otherReservation.travelerIds) &&
        Objects.equals(this.bookingInfo, otherReservation.bookingInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, date, location, description, travelerIds, bookingInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OtherReservation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    travelerIds: ").append(toIndentedString(travelerIds)).append("\n");
    sb.append("    bookingInfo: ").append(toIndentedString(bookingInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

