/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PointOfInterestCity;
import io.swagger.client.model.PointOfInterestResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PointsOfInterestResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class PointsOfInterestResponse {
  @SerializedName("current_city")
  private PointOfInterestCity currentCity = null;

  @SerializedName("points_of_interest")
  private List<PointOfInterestResult> pointsOfInterest = new ArrayList<PointOfInterestResult>();

  public PointsOfInterestResponse currentCity(PointOfInterestCity currentCity) {
    this.currentCity = currentCity;
    return this;
  }

   /**
   * Get currentCity
   * @return currentCity
  **/
  @ApiModelProperty(value = "")
  public PointOfInterestCity getCurrentCity() {
    return currentCity;
  }

  public void setCurrentCity(PointOfInterestCity currentCity) {
    this.currentCity = currentCity;
  }

  public PointsOfInterestResponse pointsOfInterest(List<PointOfInterestResult> pointsOfInterest) {
    this.pointsOfInterest = pointsOfInterest;
    return this;
  }

  public PointsOfInterestResponse addPointsOfInterestItem(PointOfInterestResult pointsOfInterestItem) {
    this.pointsOfInterest.add(pointsOfInterestItem);
    return this;
  }

   /**
   * Get pointsOfInterest
   * @return pointsOfInterest
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PointOfInterestResult> getPointsOfInterest() {
    return pointsOfInterest;
  }

  public void setPointsOfInterest(List<PointOfInterestResult> pointsOfInterest) {
    this.pointsOfInterest = pointsOfInterest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PointsOfInterestResponse pointsOfInterestResponse = (PointsOfInterestResponse) o;
    return Objects.equals(this.currentCity, pointsOfInterestResponse.currentCity) &&
        Objects.equals(this.pointsOfInterest, pointsOfInterestResponse.pointsOfInterest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentCity, pointsOfInterest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PointsOfInterestResponse {\n");
    
    sb.append("    currentCity: ").append(toIndentedString(currentCity)).append("\n");
    sb.append("    pointsOfInterest: ").append(toIndentedString(pointsOfInterest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

