/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PointOfInterestDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class PointOfInterestDetails {
  @SerializedName("short_description")
  private String shortDescription = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("wiki_page_link")
  private String wikiPageLink = null;

  public PointOfInterestDetails shortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
    return this;
  }

   /**
   * A summary of the given point
   * @return shortDescription
  **/
  @ApiModelProperty(required = true, value = "A summary of the given point")
  public String getShortDescription() {
    return shortDescription;
  }

  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }

  public PointOfInterestDetails description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A paragraph describing this point of interest
   * @return description
  **/
  @ApiModelProperty(required = true, value = "A paragraph describing this point of interest")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public PointOfInterestDetails wikiPageLink(String wikiPageLink) {
    this.wikiPageLink = wikiPageLink;
    return this;
  }

   /**
   * A link to this point of interest&amp;quot;s wikipedia page
   * @return wikiPageLink
  **/
  @ApiModelProperty(required = true, value = "A link to this point of interest&quot;s wikipedia page")
  public String getWikiPageLink() {
    return wikiPageLink;
  }

  public void setWikiPageLink(String wikiPageLink) {
    this.wikiPageLink = wikiPageLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PointOfInterestDetails pointOfInterestDetails = (PointOfInterestDetails) o;
    return Objects.equals(this.shortDescription, pointOfInterestDetails.shortDescription) &&
        Objects.equals(this.description, pointOfInterestDetails.description) &&
        Objects.equals(this.wikiPageLink, pointOfInterestDetails.wikiPageLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shortDescription, description, wikiPageLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PointOfInterestDetails {\n");
    
    sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    wikiPageLink: ").append(toIndentedString(wikiPageLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

