/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Result availble grades.
 */
@ApiModel(description = "Result availble grades.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class PointOfInterestResultGrades {
  @SerializedName("yapq_grade")
  private Integer yapqGrade = null;

  @SerializedName("city_grade")
  private Integer cityGrade = null;

  public PointOfInterestResultGrades yapqGrade(Integer yapqGrade) {
    this.yapqGrade = yapqGrade;
    return this;
  }

   /**
   * Main YAPQ grade. A grade out of 5 for this point, rated against all points in the world and normalized among selected group of points. 5 is best, 0 is worst.
   * @return yapqGrade
  **/
  @ApiModelProperty(value = "Main YAPQ grade. A grade out of 5 for this point, rated against all points in the world and normalized among selected group of points. 5 is best, 0 is worst.")
  public Integer getYapqGrade() {
    return yapqGrade;
  }

  public void setYapqGrade(Integer yapqGrade) {
    this.yapqGrade = yapqGrade;
  }

  public PointOfInterestResultGrades cityGrade(Integer cityGrade) {
    this.cityGrade = cityGrade;
    return this;
  }

   /**
   * The ranking of this point of interest compared to other points in this city. 1 is the highest rated.
   * @return cityGrade
  **/
  @ApiModelProperty(value = "The ranking of this point of interest compared to other points in this city. 1 is the highest rated.")
  public Integer getCityGrade() {
    return cityGrade;
  }

  public void setCityGrade(Integer cityGrade) {
    this.cityGrade = cityGrade;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PointOfInterestResultGrades pointOfInterestResultGrades = (PointOfInterestResultGrades) o;
    return Objects.equals(this.yapqGrade, pointOfInterestResultGrades.yapqGrade) &&
        Objects.equals(this.cityGrade, pointOfInterestResultGrades.cityGrade);
  }

  @Override
  public int hashCode() {
    return Objects.hash(yapqGrade, cityGrade);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PointOfInterestResultGrades {\n");
    
    sb.append("    yapqGrade: ").append(toIndentedString(yapqGrade)).append("\n");
    sb.append("    cityGrade: ").append(toIndentedString(cityGrade)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

