/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RailStationAutocompleteResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class RailStationAutocompleteResponse {
  @SerializedName("value")
  private String value = null;

  @SerializedName("label")
  private String label = null;

  public RailStationAutocompleteResponse value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The unique identifier of the station. You can use this as an input parameter for a rail search.
   * @return value
  **/
  @ApiModelProperty(required = true, value = "The unique identifier of the station. You can use this as an input parameter for a rail search.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public RailStationAutocompleteResponse label(String label) {
    this.label = label;
    return this;
  }

   /**
   * The full name of the station, in UTF-8 format.
   * @return label
  **/
  @ApiModelProperty(required = true, value = "The full name of the station, in UTF-8 format.")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RailStationAutocompleteResponse railStationAutocompleteResponse = (RailStationAutocompleteResponse) o;
    return Objects.equals(this.value, railStationAutocompleteResponse.value) &&
        Objects.equals(this.label, railStationAutocompleteResponse.label);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, label);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RailStationAutocompleteResponse {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

