/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Geolocation;
import java.io.IOException;

/**
 * RailStationResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class RailStationResponse {
  @SerializedName("id")
  private String id = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("short_name")
  private String shortName = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("location")
  private Geolocation location = null;

  @SerializedName("traffic")
  private String traffic = null;

  public RailStationResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of this station, as provided in the request
   * @return id
  **/
  @ApiModelProperty(required = true, value = "The ID of this station, as provided in the request")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RailStationResponse type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of code to which this station refers. Some codes represent agglomeration of multiple stations, whereas others represent an individual station. Possible values are AGGLOMERATION and STATION.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The type of code to which this station refers. Some codes represent agglomeration of multiple stations, whereas others represent an individual station. Possible values are AGGLOMERATION and STATION.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public RailStationResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of this station.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The name of this station.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RailStationResponse shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * The shortened name of this station (20 characters max) which may be used in certain cases.
   * @return shortName
  **/
  @ApiModelProperty(required = true, value = "The shortened name of this station (20 characters max) which may be used in certain cases.")
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public RailStationResponse country(String country) {
    this.country = country;
    return this;
  }

   /**
   * The &lt;a href&#x3D;\&quot;http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2\&quot;&gt;ISO 3166-1 alpha-2 country code&lt;/a&gt; in which this station can be found.
   * @return country
  **/
  @ApiModelProperty(required = true, value = "The <a href=\"http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2\">ISO 3166-1 alpha-2 country code</a> in which this station can be found.")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public RailStationResponse location(Geolocation location) {
    this.location = location;
    return this;
  }

   /**
   * This stations&#39;s approximate geolocation. 
   * @return location
  **/
  @ApiModelProperty(required = true, value = "This stations's approximate geolocation. ")
  public Geolocation getLocation() {
    return location;
  }

  public void setLocation(Geolocation location) {
    this.location = location;
  }

  public RailStationResponse traffic(String traffic) {
    this.traffic = traffic;
    return this;
  }

   /**
   * An indication of the level of Intercity traffic passing through this station.
   * @return traffic
  **/
  @ApiModelProperty(required = true, value = "An indication of the level of Intercity traffic passing through this station.")
  public String getTraffic() {
    return traffic;
  }

  public void setTraffic(String traffic) {
    this.traffic = traffic;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RailStationResponse railStationResponse = (RailStationResponse) o;
    return Objects.equals(this.id, railStationResponse.id) &&
        Objects.equals(this.type, railStationResponse.type) &&
        Objects.equals(this.name, railStationResponse.name) &&
        Objects.equals(this.shortName, railStationResponse.shortName) &&
        Objects.equals(this.country, railStationResponse.country) &&
        Objects.equals(this.location, railStationResponse.location) &&
        Objects.equals(this.traffic, railStationResponse.traffic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, name, shortName, country, location, traffic);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RailStationResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    traffic: ").append(toIndentedString(traffic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

