/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Amount;
import java.io.IOException;

/**
 * Rate
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class Rate {
  @SerializedName("type")
  private String type = null;

  @SerializedName("price")
  private Amount price = null;

  public Rate type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type or applicability period of rate being applied. For example&amp;colon; DAILY, WEEKLY, WEEKEND.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The type or applicability period of rate being applied. For example&colon; DAILY, WEEKLY, WEEKEND.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Rate price(Amount price) {
    this.price = price;
    return this;
  }

   /**
   * The long name of the provider corresponding to the above code.
   * @return price
  **/
  @ApiModelProperty(required = true, value = "The long name of the provider corresponding to the above code.")
  public Amount getPrice() {
    return price;
  }

  public void setPrice(Amount price) {
    this.price = price;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rate rate = (Rate) o;
    return Objects.equals(this.type, rate.type) &&
        Objects.equals(this.price, rate.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, price);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rate {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

