/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CarReservation;
import io.swagger.client.model.FlightReservationBound;
import io.swagger.client.model.FlightTicket;
import io.swagger.client.model.HotelReservation;
import io.swagger.client.model.OtherReservation;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Reservation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class Reservation {
  @SerializedName("flight_tickets")
  private FlightTicket flightTickets = null;

  @SerializedName("unticketed_flights")
  private List<FlightReservationBound> unticketedFlights = null;

  @SerializedName("cars")
  private List<CarReservation> cars = null;

  @SerializedName("hotels")
  private List<HotelReservation> hotels = null;

  @SerializedName("others")
  private List<OtherReservation> others = null;

  public Reservation flightTickets(FlightTicket flightTickets) {
    this.flightTickets = flightTickets;
    return this;
  }

   /**
   * Get flightTickets
   * @return flightTickets
  **/
  @ApiModelProperty(value = "")
  public FlightTicket getFlightTickets() {
    return flightTickets;
  }

  public void setFlightTickets(FlightTicket flightTickets) {
    this.flightTickets = flightTickets;
  }

  public Reservation unticketedFlights(List<FlightReservationBound> unticketedFlights) {
    this.unticketedFlights = unticketedFlights;
    return this;
  }

  public Reservation addUnticketedFlightsItem(FlightReservationBound unticketedFlightsItem) {
    if (this.unticketedFlights == null) {
      this.unticketedFlights = new ArrayList<FlightReservationBound>();
    }
    this.unticketedFlights.add(unticketedFlightsItem);
    return this;
  }

   /**
   * The flight itineraries in this reservation that have not yet been ticketed or priced.
   * @return unticketedFlights
  **/
  @ApiModelProperty(value = "The flight itineraries in this reservation that have not yet been ticketed or priced.")
  public List<FlightReservationBound> getUnticketedFlights() {
    return unticketedFlights;
  }

  public void setUnticketedFlights(List<FlightReservationBound> unticketedFlights) {
    this.unticketedFlights = unticketedFlights;
  }

  public Reservation cars(List<CarReservation> cars) {
    this.cars = cars;
    return this;
  }

  public Reservation addCarsItem(CarReservation carsItem) {
    if (this.cars == null) {
      this.cars = new ArrayList<CarReservation>();
    }
    this.cars.add(carsItem);
    return this;
  }

   /**
   * The rental cars reserved.
   * @return cars
  **/
  @ApiModelProperty(value = "The rental cars reserved.")
  public List<CarReservation> getCars() {
    return cars;
  }

  public void setCars(List<CarReservation> cars) {
    this.cars = cars;
  }

  public Reservation hotels(List<HotelReservation> hotels) {
    this.hotels = hotels;
    return this;
  }

  public Reservation addHotelsItem(HotelReservation hotelsItem) {
    if (this.hotels == null) {
      this.hotels = new ArrayList<HotelReservation>();
    }
    this.hotels.add(hotelsItem);
    return this;
  }

   /**
   * The hotel room bookings in this reservation.
   * @return hotels
  **/
  @ApiModelProperty(value = "The hotel room bookings in this reservation.")
  public List<HotelReservation> getHotels() {
    return hotels;
  }

  public void setHotels(List<HotelReservation> hotels) {
    this.hotels = hotels;
  }

  public Reservation others(List<OtherReservation> others) {
    this.others = others;
    return this;
  }

  public Reservation addOthersItem(OtherReservation othersItem) {
    if (this.others == null) {
      this.others = new ArrayList<OtherReservation>();
    }
    this.others.add(othersItem);
    return this;
  }

   /**
   * Free text information to represent other travel items that may be considered part of the travel itinerary in this reservation.
   * @return others
  **/
  @ApiModelProperty(value = "Free text information to represent other travel items that may be considered part of the travel itinerary in this reservation.")
  public List<OtherReservation> getOthers() {
    return others;
  }

  public void setOthers(List<OtherReservation> others) {
    this.others = others;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Reservation reservation = (Reservation) o;
    return Objects.equals(this.flightTickets, reservation.flightTickets) &&
        Objects.equals(this.unticketedFlights, reservation.unticketedFlights) &&
        Objects.equals(this.cars, reservation.cars) &&
        Objects.equals(this.hotels, reservation.hotels) &&
        Objects.equals(this.others, reservation.others);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flightTickets, unticketedFlights, cars, hotels, others);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Reservation {\n");
    
    sb.append("    flightTickets: ").append(toIndentedString(flightTickets)).append("\n");
    sb.append("    unticketedFlights: ").append(toIndentedString(unticketedFlights)).append("\n");
    sb.append("    cars: ").append(toIndentedString(cars)).append("\n");
    sb.append("    hotels: ").append(toIndentedString(hotels)).append("\n");
    sb.append("    others: ").append(toIndentedString(others)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

