/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * More detailed structured information about the room.
 */
@ApiModel(description = "More detailed structured information about the room.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class RoomInfo {
  @SerializedName("bed_type")
  private String bedType = null;

  @SerializedName("number_of_beds")
  private String numberOfBeds = null;

  @SerializedName("room_type")
  private String roomType = null;

  public RoomInfo bedType(String bedType) {
    this.bedType = bedType;
    return this;
  }

   /**
   * The type of bed or beds in the room, such as Double, or King.
   * @return bedType
  **/
  @ApiModelProperty(required = true, value = "The type of bed or beds in the room, such as Double, or King.")
  public String getBedType() {
    return bedType;
  }

  public void setBedType(String bedType) {
    this.bedType = bedType;
  }

  public RoomInfo numberOfBeds(String numberOfBeds) {
    this.numberOfBeds = numberOfBeds;
    return this;
  }

   /**
   * The number of beds in the room. May be an integer or a free-text dessciption, as provided by the hotel
   * @return numberOfBeds
  **/
  @ApiModelProperty(required = true, value = "The number of beds in the room. May be an integer or a free-text dessciption, as provided by the hotel")
  public String getNumberOfBeds() {
    return numberOfBeds;
  }

  public void setNumberOfBeds(String numberOfBeds) {
    this.numberOfBeds = numberOfBeds;
  }

  public RoomInfo roomType(String roomType) {
    this.roomType = roomType;
    return this;
  }

   /**
   * Free-text indicating the type of room - such Smoking, No Smoking, Suite, etc..
   * @return roomType
  **/
  @ApiModelProperty(required = true, value = "Free-text indicating the type of room - such Smoking, No Smoking, Suite, etc..")
  public String getRoomType() {
    return roomType;
  }

  public void setRoomType(String roomType) {
    this.roomType = roomType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoomInfo roomInfo = (RoomInfo) o;
    return Objects.equals(this.bedType, roomInfo.bedType) &&
        Objects.equals(this.numberOfBeds, roomInfo.numberOfBeds) &&
        Objects.equals(this.roomType, roomInfo.roomType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bedType, numberOfBeds, roomType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoomInfo {\n");
    
    sb.append("    bedType: ").append(toIndentedString(bedType)).append("\n");
    sb.append("    numberOfBeds: ").append(toIndentedString(numberOfBeds)).append("\n");
    sb.append("    roomType: ").append(toIndentedString(roomType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

