/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TopSearchesSearchResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TopSearchesSearchResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class TopSearchesSearchResponse {
  @SerializedName("market")
  private String market = null;

  @SerializedName("period")
  private String period = null;

  @SerializedName("origin")
  private String origin = null;

  @SerializedName("destination")
  private String destination = null;

  @SerializedName("results")
  private List<TopSearchesSearchResult> results = new ArrayList<TopSearchesSearchResult>();

  public TopSearchesSearchResponse market(String market) {
    this.market = market;
    return this;
  }

   /**
   * Country code
   * @return market
  **/
  @ApiModelProperty(required = true, value = "Country code")
  public String getMarket() {
    return market;
  }

  public void setMarket(String market) {
    this.market = market;
  }

  public TopSearchesSearchResponse period(String period) {
    this.period = period;
    return this;
  }

   /**
   * The date period, in &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/ISO_8601\&quot;&gt;ISO 8601&lt;/a&gt; date format YYYY-MM or YYYY
   * @return period
  **/
  @ApiModelProperty(required = true, value = "The date period, in <a href=\"https://en.wikipedia.org/wiki/ISO_8601\">ISO 8601</a> date format YYYY-MM or YYYY")
  public String getPeriod() {
    return period;
  }

  public void setPeriod(String period) {
    this.period = period;
  }

  public TopSearchesSearchResponse origin(String origin) {
    this.origin = origin;
    return this;
  }

   /**
   * &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\&quot;&gt;IATA code&lt;/a&gt;
   * @return origin
  **/
  @ApiModelProperty(required = true, value = "<a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a>")
  public String getOrigin() {
    return origin;
  }

  public void setOrigin(String origin) {
    this.origin = origin;
  }

  public TopSearchesSearchResponse destination(String destination) {
    this.destination = destination;
    return this;
  }

   /**
   * &lt;a href&#x3D;\&quot;https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\&quot;&gt;IATA code&lt;/a&gt;
   * @return destination
  **/
  @ApiModelProperty(required = true, value = "<a href=\"https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code\">IATA code</a>")
  public String getDestination() {
    return destination;
  }

  public void setDestination(String destination) {
    this.destination = destination;
  }

  public TopSearchesSearchResponse results(List<TopSearchesSearchResult> results) {
    this.results = results;
    return this;
  }

  public TopSearchesSearchResponse addResultsItem(TopSearchesSearchResult resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(required = true, value = "")
  public List<TopSearchesSearchResult> getResults() {
    return results;
  }

  public void setResults(List<TopSearchesSearchResult> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TopSearchesSearchResponse topSearchesSearchResponse = (TopSearchesSearchResponse) o;
    return Objects.equals(this.market, topSearchesSearchResponse.market) &&
        Objects.equals(this.period, topSearchesSearchResponse.period) &&
        Objects.equals(this.origin, topSearchesSearchResponse.origin) &&
        Objects.equals(this.destination, topSearchesSearchResponse.destination) &&
        Objects.equals(this.results, topSearchesSearchResponse.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(market, period, origin, destination, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TopSearchesSearchResponse {\n");
    
    sb.append("    market: ").append(toIndentedString(market)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

