/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Amount;
import io.swagger.client.model.RestrictedRate;
import java.io.IOException;

/**
 * TrainSearchPricing
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class TrainSearchPricing {
  @SerializedName("service_class")
  private String serviceClass = null;

  @SerializedName("booking_code")
  private String bookingCode = null;

  @SerializedName("accomodation")
  private String accomodation = null;

  @SerializedName("total_price")
  private Amount totalPrice = null;

  @SerializedName("rate")
  private RestrictedRate rate = null;

  public TrainSearchPricing serviceClass(String serviceClass) {
    this.serviceClass = serviceClass;
    return this;
  }

   /**
   * A standard enumeration of the type of seat, bed or service the passenger can expect.
   * @return serviceClass
  **/
  @ApiModelProperty(required = true, value = "A standard enumeration of the type of seat, bed or service the passenger can expect.")
  public String getServiceClass() {
    return serviceClass;
  }

  public void setServiceClass(String serviceClass) {
    this.serviceClass = serviceClass;
  }

  public TrainSearchPricing bookingCode(String bookingCode) {
    this.bookingCode = bookingCode;
    return this;
  }

   /**
   * A code the identifies the type of booking class being used.
   * @return bookingCode
  **/
  @ApiModelProperty(required = true, value = "A code the identifies the type of booking class being used.")
  public String getBookingCode() {
    return bookingCode;
  }

  public void setBookingCode(String bookingCode) {
    this.bookingCode = bookingCode;
  }

  public TrainSearchPricing accomodation(String accomodation) {
    this.accomodation = accomodation;
    return this;
  }

   /**
   * A standard enumeration of the mode in which the passenger is accommodated. For example&amp;colon; SEAT, BERTH, CABIN, CARGO, UNKNOWN.
   * @return accomodation
  **/
  @ApiModelProperty(required = true, value = "A standard enumeration of the mode in which the passenger is accommodated. For example&colon; SEAT, BERTH, CABIN, CARGO, UNKNOWN.")
  public String getAccomodation() {
    return accomodation;
  }

  public void setAccomodation(String accomodation) {
    this.accomodation = accomodation;
  }

  public TrainSearchPricing totalPrice(Amount totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

   /**
   * The total cost of this service.
   * @return totalPrice
  **/
  @ApiModelProperty(required = true, value = "The total cost of this service.")
  public Amount getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(Amount totalPrice) {
    this.totalPrice = totalPrice;
  }

  public TrainSearchPricing rate(RestrictedRate rate) {
    this.rate = rate;
    return this;
  }

   /**
   * A rate identifying type of charge being levied for this service, and the restrictions that apply.
   * @return rate
  **/
  @ApiModelProperty(required = true, value = "A rate identifying type of charge being levied for this service, and the restrictions that apply.")
  public RestrictedRate getRate() {
    return rate;
  }

  public void setRate(RestrictedRate rate) {
    this.rate = rate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainSearchPricing trainSearchPricing = (TrainSearchPricing) o;
    return Objects.equals(this.serviceClass, trainSearchPricing.serviceClass) &&
        Objects.equals(this.bookingCode, trainSearchPricing.bookingCode) &&
        Objects.equals(this.accomodation, trainSearchPricing.accomodation) &&
        Objects.equals(this.totalPrice, trainSearchPricing.totalPrice) &&
        Objects.equals(this.rate, trainSearchPricing.rate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceClass, bookingCode, accomodation, totalPrice, rate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainSearchPricing {\n");
    
    sb.append("    serviceClass: ").append(toIndentedString(serviceClass)).append("\n");
    sb.append("    bookingCode: ").append(toIndentedString(bookingCode)).append("\n");
    sb.append("    accomodation: ").append(toIndentedString(accomodation)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

