/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RailService;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;

/**
 * TrainScheduleSearchResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class TrainScheduleSearchResult {
  @SerializedName("origin_station_id")
  private String originStationId = null;

  @SerializedName("date")
  private LocalDate date = null;

  @SerializedName("services")
  private List<RailService> services = new ArrayList<RailService>();

  public TrainScheduleSearchResult originStationId(String originStationId) {
    this.originStationId = originStationId;
    return this;
  }

   /**
   * Station ID of the origin station for this search.
   * @return originStationId
  **/
  @ApiModelProperty(required = true, value = "Station ID of the origin station for this search.")
  public String getOriginStationId() {
    return originStationId;
  }

  public void setOriginStationId(String originStationId) {
    this.originStationId = originStationId;
  }

  public TrainScheduleSearchResult date(LocalDate date) {
    this.date = date;
    return this;
  }

   /**
   * The search date provided in the input.
   * @return date
  **/
  @ApiModelProperty(required = true, value = "The search date provided in the input.")
  public LocalDate getDate() {
    return date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }

  public TrainScheduleSearchResult services(List<RailService> services) {
    this.services = services;
    return this;
  }

  public TrainScheduleSearchResult addServicesItem(RailService servicesItem) {
    this.services.add(servicesItem);
    return this;
  }

   /**
   * Array to describe service to the destinations.
   * @return services
  **/
  @ApiModelProperty(required = true, value = "Array to describe service to the destinations.")
  public List<RailService> getServices() {
    return services;
  }

  public void setServices(List<RailService> services) {
    this.services = services;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainScheduleSearchResult trainScheduleSearchResult = (TrainScheduleSearchResult) o;
    return Objects.equals(this.originStationId, trainScheduleSearchResult.originStationId) &&
        Objects.equals(this.date, trainScheduleSearchResult.date) &&
        Objects.equals(this.services, trainScheduleSearchResult.services);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originStationId, date, services);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainScheduleSearchResult {\n");
    
    sb.append("    originStationId: ").append(toIndentedString(originStationId)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

