/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TrainSearchSegment;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TrainSearchItinerary
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class TrainSearchItinerary {
  @SerializedName("trains")
  private List<TrainSearchSegment> trains = new ArrayList<TrainSearchSegment>();

  public TrainSearchItinerary trains(List<TrainSearchSegment> trains) {
    this.trains = trains;
    return this;
  }

  public TrainSearchItinerary addTrainsItem(TrainSearchSegment trainsItem) {
    this.trains.add(trainsItem);
    return this;
  }

   /**
   * The array of trains that will be required to complete the given itinerary. Since the cache currently only contains direct itineraries, there will be only one object in this array.
   * @return trains
  **/
  @ApiModelProperty(required = true, value = "The array of trains that will be required to complete the given itinerary. Since the cache currently only contains direct itineraries, there will be only one object in this array.")
  public List<TrainSearchSegment> getTrains() {
    return trains;
  }

  public void setTrains(List<TrainSearchSegment> trains) {
    this.trains = trains;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainSearchItinerary trainSearchItinerary = (TrainSearchItinerary) o;
    return Objects.equals(this.trains, trainSearchItinerary.trains);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trains);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainSearchItinerary {\n");
    
    sb.append("    trains: ").append(toIndentedString(trains)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

