/*
 * Amadeus Travel Innovation Sandbox
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VehicleInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-24T09:42:17.291Z")
public class VehicleInfo {
  @SerializedName("acriss_code")
  private String acrissCode = null;

  @SerializedName("category")
  private String category = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("transmission")
  private String transmission = null;

  @SerializedName("air_conditioning")
  private Boolean airConditioning = null;

  @SerializedName("fuel")
  private String fuel = null;

  public VehicleInfo acrissCode(String acrissCode) {
    this.acrissCode = acrissCode;
    return this;
  }

   /**
   * The 4 letter &lt;a href&#x3D;\&quot;http://en.wikipedia.org/wiki/ACRISS_Car_Classification_Code\&quot;&gt;ACRISS code&lt;/a&gt; that defines the properties of vehicle being rented.
   * @return acrissCode
  **/
  @ApiModelProperty(required = true, value = "The 4 letter <a href=\"http://en.wikipedia.org/wiki/ACRISS_Car_Classification_Code\">ACRISS code</a> that defines the properties of vehicle being rented.")
  public String getAcrissCode() {
    return acrissCode;
  }

  public void setAcrissCode(String acrissCode) {
    this.acrissCode = acrissCode;
  }

  public VehicleInfo category(String category) {
    this.category = category;
    return this;
  }

   /**
   * The decoded ACRISS vehicle category (For example&amp;colon; Economy, Luxury, Standard).
   * @return category
  **/
  @ApiModelProperty(required = true, value = "The decoded ACRISS vehicle category (For example&colon; Economy, Luxury, Standard).")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public VehicleInfo type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The decoded ACRISS vehicle type, to let you know what kind of vehicle this is (For example&amp;colon; Van, SUV, Pickup).
   * @return type
  **/
  @ApiModelProperty(value = "The decoded ACRISS vehicle type, to let you know what kind of vehicle this is (For example&colon; Van, SUV, Pickup).")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public VehicleInfo transmission(String transmission) {
    this.transmission = transmission;
    return this;
  }

   /**
   * The decoded ACRISS transmission type, to let you know if this vehicle is Automatic or Manual Transmission (stick-shift).
   * @return transmission
  **/
  @ApiModelProperty(value = "The decoded ACRISS transmission type, to let you know if this vehicle is Automatic or Manual Transmission (stick-shift).")
  public String getTransmission() {
    return transmission;
  }

  public void setTransmission(String transmission) {
    this.transmission = transmission;
  }

  public VehicleInfo airConditioning(Boolean airConditioning) {
    this.airConditioning = airConditioning;
    return this;
  }

   /**
   * The decoded ACRISS air_conditioning information, to let you know if this vehicle has air conditioning
   * @return airConditioning
  **/
  @ApiModelProperty(value = "The decoded ACRISS air_conditioning information, to let you know if this vehicle has air conditioning")
  public Boolean isAirConditioning() {
    return airConditioning;
  }

  public void setAirConditioning(Boolean airConditioning) {
    this.airConditioning = airConditioning;
  }

  public VehicleInfo fuel(String fuel) {
    this.fuel = fuel;
    return this;
  }

   /**
   * The decoded ACRISS fuel type, to let you know if this vehicle is hybrid, electric, etc.
   * @return fuel
  **/
  @ApiModelProperty(value = "The decoded ACRISS fuel type, to let you know if this vehicle is hybrid, electric, etc.")
  public String getFuel() {
    return fuel;
  }

  public void setFuel(String fuel) {
    this.fuel = fuel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VehicleInfo vehicleInfo = (VehicleInfo) o;
    return Objects.equals(this.acrissCode, vehicleInfo.acrissCode) &&
        Objects.equals(this.category, vehicleInfo.category) &&
        Objects.equals(this.type, vehicleInfo.type) &&
        Objects.equals(this.transmission, vehicleInfo.transmission) &&
        Objects.equals(this.airConditioning, vehicleInfo.airConditioning) &&
        Objects.equals(this.fuel, vehicleInfo.fuel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acrissCode, category, type, transmission, airConditioning, fuel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VehicleInfo {\n");
    
    sb.append("    acrissCode: ").append(toIndentedString(acrissCode)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    transmission: ").append(toIndentedString(transmission)).append("\n");
    sb.append("    airConditioning: ").append(toIndentedString(airConditioning)).append("\n");
    sb.append("    fuel: ").append(toIndentedString(fuel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

